src/main.rs
Extended permissions test to validate the RpcProvider does not give Admin permissions.
=> Extended permissions test

API.md, README.md, candid/ic_eth.did, scripts/local, src/accounting.rs, src/constants.rs, src/http.rs, src/main.rs, src/types.rs
This PR changes the `request` and `request_cost` methods to receive `Source` variants which can represent URLs, registered providers, or [EVM chain identifiers](https://chainlist.org/?testnets=true). This provides a layer of abstraction for more realistic use cases where the developer wants to call an RPC method on a specific EVM network without needing to know which specific RPC provider is being used behind the scenes. 
At the moment, the "preferred provider" for a given network is defined as the earliest registered provider with the `active` flag set to `true`.
=> Simplify calling a specific EVM network

API.md, candid/ic_eth.did, src/accounting.rs, src/main.rs, src/types.rs
This PR makes it possible for administrators to change the default canister for the `Chain` source variant by enabling the `primary` flag via `update_provider`. This will be important for gradually deprecating RPC providers when necessary in production.
=> Refactor `active` to `primary` in RPC providers

src/main.rs, src/providers.rs
This PR changes the `update_provider` RPC method to use the `RegisterProvider` authorization (in place of `Admin`) to manage API keys.
=> Adjust permissions for `update_provider` method

API.md, candid/ic_eth.did, src/accounting.rs, src/main.rs, src/providers.rs, src/types.rs, src/validate.rs
Includes `#Service : {base_url : text, chain_id : opt nat64}` as an alternative to `#Provider : nat64` for the `request` and `request_cost` methods.
=> Add `Service` source variant

Cargo.lock, src/constants.rs, src/providers.rs
The canister now uses the following list of default JSON-RPC providers, available without API keys for usage in the local replica:
- `cloudflare-eth.com` (Ethereum mainnet)
- `rpc.ankr.com` (Ethereum mainnet)
- `ethereum.blockpi.network` (Ethereum mainnet)
- `rpc.sepolia.org` (Sepolia testnet)
- `ethereum-sepolia.publicnode.com` (Sepolia testnet)
=> Update default RPC providers

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/candid_rpc.rs, src/constants.rs, src/lib.rs, src/main.rs, src/types.rs, tests/tests.rs
Configures testing via the `ic_state_machine_tests` crate using similar conventions to the ckETH codebase. 
Resolves #77.
**Next steps:**
- Mock HTTPS outcalls
- Add tests for each Candid-RPC method
=> Set up IC state machine tests

Cargo.lock, candid/evm_rpc.did, src/candid_rpc.rs, src/constants.rs, src/providers.rs
This PR changes the Candid-RPC methods to use registered `RpcProvider` API keys (previously only used for generic JSON-RPC requests).
Resolves #73.
=> feat: use registered API keys in Candid-RPC methods

Cargo.lock, Cargo.toml, candid/evm_rpc.did, src/candid_rpc.rs, src/constants.rs, src/providers.rs, src/types.rs, tests/tests.rs
* Adds a new `EthMainnetService::PublicNode` variant and default provider
* Refactors to account for changes to the ckETH codebase over the past few weeks
=> chore: update providers based on new ckETH repo changes

Cargo.lock, Cargo.toml, candid/evm_rpc.did, scripts/examples, src/candid_rpc.rs, src/main.rs, src/providers.rs, src/types.rs, tests/tests.rs
Previously, the EVM RPC canister only returned JSON object properties used in ckETH. This PR adds the corresponding Candid record fields for all remaining properties.
=> feat!: include all JSON properties in Candid-RPC responses

Cargo.lock, Cargo.toml
Includes a specific commit hash for the forked ckETH codebase. 
Resolves #74.
I opened a corresponding MR ([!16803](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/16803)) in the [`dfinity-lab/public/ic`](https://gitlab.com/dfinity-lab/public/ic) GitLab repository, but this unfortunately cannot be used in an open-source context due to requiring authentication. One solution could be to mirror this branch in the [`dfinity/ic`](https://github.com/dfinity/ic) GitHub repository.
=> chore: add Git hash to external repository

canister_ids.json, e2e/motoko/Main.mo, e2e/rust/src/main.rs
This PR adds access control to the Rust and Motoko E2E tests and includes the deployed principals in `canister_ids.json`. 
Resolves #78.
=> chore: set up mainnet E2E testing environment

e2e/motoko/Main.mo, lib/motoko/src/lib.mo
Adjusts the Motoko E2E test canister to call the actual Ethereum mainnet RPC providers. This also serves as reference for calling the EVM RPC canister from Motoko.
=> test: call Candid-RPC methods from Motoko E2E canister

.gitignore, candid/evm_rpc.did, e2e/motoko/Main.mo, package.json, src/main.rs
Resolves #76.
CC @gregorydemay.
=> refactor: custom names for generic result types in Candid interface

src/accounting.rs, src/candid_rpc.rs, src/http.rs, src/main.rs
Follow-up from #86. 
This adds some minor performance overhead in exchange for a slightly cleaner codebase.
=> refactor: convert `payload_size_bytes` from `usize` to `u64`

Cargo.lock, Cargo.toml, candid/evm_rpc.did, e2e/motoko/Main.mo, src/candid_rpc.rs, src/constants.rs, src/providers.rs
Includes [Alchemy](https://www.alchemy.com/) in the list of built-in RPC services.
=> feat: add Alchemy to RPC service list

candid/evm_rpc.did, src/types.rs
This PR adjusts the fields in the `Metrics` record to use camelCase instead of snake_case for consistency with the RPC methods and canister install arguments.
=> fix: change case of metric fields in Candid interface

candid/evm_rpc.did, src/auth.rs, src/providers.rs, src/types.rs, tests/tests.rs
Open to other naming suggestions! 
Follow-up from #122.
=> refactor: rename `ManageCanister` authorization to `Manage`

Cargo.lock, e2e/motoko/Main.mo, src/accounting.rs, src/candid_rpc.rs, src/constants.rs
Removes `get_candid_rpc_cost()` (cost calculation from ckETH) in favor of the more precise `get_http_request_cost()`. This PR also updates the HTTP outcall prices to reflect the latest values [from the developer docs](https://internetcomputer.org/docs/current/developer-docs/gas-cost).
Closes #129.
=> fix: adjust cycles cost calculation

Cargo.lock, Cargo.toml, candid/evm_rpc.did, src/candid_rpc.rs, src/http.rs, src/main.rs, src/metrics.rs, src/types.rs, tests/tests.rs
Adds the following metrics:
- `responses` now records the HTTP status codes for JSON-RPC responses.
- `inconsistent_responses` counts the number of `MultiRpcResult::Inconsistent(..)` results for each combination of RPC method and hostname.
Another notable change (not represented in the diff of this PR) is that I adjusted the implementation of `MultiCallResult::all_ok()` in the forked ckETH codebase to return all results in the case of an error. Otherwise, an RPC service could bypass the agreement / consistency logic by returning an error for an otherwise successful RPC request.
=> metrics: HTTP status codes and inconsistent responses

e2e/motoko/Main.mo
Ignores errors which occasionally occur in CI when calling `eth_sendRawTransaction` with the BlockPI RPC service.
=> chore: add ignored service/method combinations in Motoko E2E testing

Cargo.lock, Cargo.toml
Replaces a personal GitHub fork with the [`evm-rpc-canister`](https://github.com/dfinity/ic/tree/evm-rpc-canister) branch mirrored onto the `dfinity/ic` GitHub repository.
=> chore: point `cketh-common` to official `dfinity/ic` repository

src/metrics.rs
This is mostly for consistency with ckETH. Also adds a `cycle_balance{canister="evmrpc"}` metric.
=> metrics: add `evmrpc` prefix to Prometheus metric names

Cargo.lock, Cargo.toml, candid/evm_rpc.did, e2e/motoko/Main.mo, src/candid_rpc.rs, src/constants.rs, src/main.rs, tests/mock.rs, tests/tests.rs
Makes it possible to specify a custom response size estimate for any Candid-RPC method. This also gives us a way to add more configuration options (e.g. consensus/agreement policy) in a backwards-compatible manner.
=> feat!: add `RpcConfig` arg to Candid-RPC methods

Cargo.lock, Cargo.toml, candid/evm_rpc.did, src/candid_rpc.rs, src/main.rs, src/types.rs, src/validate.rs
Removes all `TraceHttp` log entries from the public `/logs` API endpoint, since these messages could include API keys of custom RPC service URIs or other potentially sensitive information. 
I also removed the `Debug` trait from anything storing an API key to ensure that we cannot accidentally include these in log messages.
=> logs: remove `TraceHttp` entries from HTTP endpoint

e2e/motoko/Main.mo
Makes it possible to differentiate between the 13-node and fiduciary subnets while running E2E tests on the IC mainnet.
=> chore: add subnet type in E2E console messages

e2e/motoko/Main.mo
Changes the Motoko E2E test to run all tests and then show a summary of errors.
=> test: show all errors at end of Motoko E2E tests

candid/evm_rpc.did, src/auth.rs, src/main.rs, src/providers.rs, tests/tests.rs
* Allows controllers to update and unregister providers
* Improves readability of `do_authorize` and `do_deauthorize`
* Prevents accidentally authorizing the anonymous principal
=> auth: miscellaneous

e2e/motoko/Main.mo, src/accounting.rs, src/constants.rs
The original Ethereum integration and ckETH cycles calculation logic used a linear approximation of the HTTP outcall cycles cost calculation. This PR uses the exact formula, which includes a quadratic term: 
`((3M + 60K * nodes_in_subnet) + 400 * request_size + 800 * max_response) * nodes_in_subnet`
I also added a link to the (somewhat difficult-to-find) documentation page knowing that some community members are using this code as reference for calculating HTTP outcall costs.
=> fix: use exact formula for HTTP outcall cost calculation

src/providers.rs, src/types.rs, tests/tests.rs
Follow-up from the implementation review.
=> auth: remove ability for `Auth::Manage` principal to change provider ownership

src/auth.rs, src/main.rs, src/providers.rs
* Finishes some leftover refactoring from the original Ethereum integration canister.
* Drops the requirement for the `RegisterProvider` permission and allows controller principals to withdraw cycles, making this equivalent to other methods with ownership-based authorization.
* Renames stable memory access methods for consistency with the public methods in the Candid interface.
* Renames guard `require_admin_or_controller` to `require_manage_or_controller`.
=> auth: misc. adjustments and refactoring

.github/workflows/ci.yml, README.md, canister_ids.json, dfx.json, e2e/motoko/Main.mo, e2e/rust/build.rs, e2e/rust/src/main.rs, lib/motoko/src/lib.mo, scripts/e2e
Adds a production canister deployed on the fiduciary subnet with DFINITY-managed API keys. 
In addition, this PR does a significant refactor of the Motoko E2E tests to allow testing backwards compatibility on mainnet. I also included some CI changes such as running the example dfx commands as part of the `e2e` workflow.
=> feat: set up production canister

candid/evm_rpc.did, dfx.json, e2e/motoko/Main.mo, scripts/e2e, src/accounting.rs, src/constants.rs, src/main.rs, src/memory.rs, tests/tests.rs
Adds a test for the number of subnet nodes and makes several changes to minimize the chance of the number unexpectedly changing after upgrading the canister. 
Includes changes from #168 (merging this afterwards).
=> test(e2e): number of nodes in subnet

README.md
Adds a link to ckETH, which released after writing the initial readme file.
=> docs: add link to ckETH in readme

e2e/motoko/Main.mo
Testing for custom EVM chains in the Candid-RPC methods, focusing specifically on L2 chains for the time being (which are the most likely to conform to the Ethereum JSON-RPC spec). 
Follow-up for #158.
=> test: add L2 chains to Motoko E2E tests

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, candid/evm_rpc.did, rust-toolchain.toml, src/candid_rpc.rs, src/main.rs, src/types.rs, tests/tests.rs
Modifies the Candid interface to return a computed transaction hash with the `SendRawTransactionStatus::Ok` variant. 
If there is an error while parsing the transaction hash, the method returns `Ok(null)`. This is for compatibility with custom chains which may not use exactly the same binary format for signed transactions. 
This PR also updates the Rust toolchain version from `1.70` to `1.76` for compatibility with the latest Rust version in CI.
=> feat!: return transaction hash from `eth_sendRawTransaction`

candid/evm_rpc.did
This PR adds human-readable names to otherwise ambiguous input/output values in the Candid interface. This has no effect on functionality and is purely for documentation purposes.
=> docs: add parameter names in Candid interface

candid/evm_rpc.did
Adjusts the names of several method parameters for clarity.
=> fix: update Candid interface

Cargo.lock, Cargo.toml, e2e/motoko/Main.mo, src/main.rs
This PR patches what might be considered a bug with [`ic-canister-log`](https://crates.io/crates/ic-canister-log) which occurs when creating log messages from external crates. When calling from an external crate, log messages may include absolute file paths from the machine that built the Wasm file. We fix this by truncating unknown file paths.
Corresponding MR: [!18445](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/18445).
Note that the CI for this PR depends on [!18445](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/18445) being merged.
=> fix: rewrite absolute paths in log messages

Cargo.lock, Cargo.toml, dfx.json, e2e/rust/Cargo.toml
Temporarily specifies `dfx` 0.18.0 to unblock #193. Also includes a few changes in preparation for upgrading to 0.19.0.
=> fix: dfx version in CI

candid/evm_rpc.did
Replaces `vec vec text` with `vec Topic` and includes a comment for clarity.
=> candid: clarify `topics` in `eth_getLogs` args

Cargo.lock, e2e/rust/src/main.rs
Since this is already covered by the Motoko E2E tests, this primarily serves as documentation for how to use the EVM RPC canister from Rust. Note that this is currently very low-level and verbose until we build a caller-side library to provide generic type definitions.
=> test: add example Candid-RPC method to Rust E2E test

src/providers.rs
Public Node recently deprecated the original JSON-RPC URLs. This PR updates the canister to use the new endpoint URLs by default:
* https://ethereum.publicnode.com -> https://ethereum-rpc.publicnode.com
* https://ethereum-sepolia.publicnode.com -> https://ethereum-sepolia-rpc.publicnode.com
=> rpc: update default Public Node JSON-RPC URLs

candid/evm_rpc.did, providers.did, src/providers.rs, src/types.rs, tests/tests.rs
This change makes it possible for principals with the `Manage` permission to modify previously registered chain IDs.
=> feat: ability to update chain IDs via `manageProvider` method

README.md, dfx.json
This PR simplifies local development via the new `init_arg` field in the project's `dfx.json` file.
=> dfx: add default canister init args

Cargo.lock, Cargo.toml, candid/evm_rpc.did, e2e/motoko/main.mo, src/providers.rs
Includes Llama RPC providers in the local replica and updates the Candid interface.
Pending [!19761](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19761).
=> Add Llama RPC providers

.github/workflows/ci.yml
Addresses a CI warning by updating the `setup-protoc` action.
Depends on #227 (merging will fix the error in this PR).
=> ci: bump `setup-protoc` action to v3

src/main.rs
This PR increases visibility of principals with internal authorizations for transparency.
=> auth: allow any principal to call `getAuthorized`

e2e/motoko/main.mo
Skips testing the combination of Ankr + Arbitrum One + `eth_getLogs`, which often results in "Timeout expired" error messages in CI.
=> ci: skip flaky test

candid/evm_rpc.did, src/providers.rs, src/types.rs, tests/tests.rs
This is a simplified iteration on #224 to reduce the immutability of RPC providers. 
The only change is the removal of the ability to modify the hostname and cycles costs of existing providers.
=> candid: remove hostname from `UpdateProviderArgs`

Cargo.lock, Cargo.toml, candid/evm_rpc.did, tests/tests.rs
Fixes #233 by making the following fields optional:
1. `totalDifficulty`
2. `difficulty`
3. `baseFeePerGas`
=> fix: optional fields in `Block`

README.md
Adjusts the name of the "IC 🔗 ETH" starter project to "ICP 🔗 ETH" (renamed since writing this readme).
=> docs: minimal change to readme

.gitignore, Cargo.lock, Cargo.toml, e2e/rust/Cargo.toml, evm_rpc_types/CHANGELOG.md, evm_rpc_types/Cargo.toml, evm_rpc_types/README.md, evm_rpc_types/src/lib.rs, evm_rpc_types/src/request/mod.rs, evm_rpc_types/src/response/mod.rs, evm_rpc_types/src/tests.rs, src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/main.rs, src/types.rs, tests/tests.rs
Introduce a new crate `evm_rpc_types` that will contain all Candid types necessary to interact with the EVM RPC canister. As a first step for #243 :
1. Introduce `Nat256` as a wrapper around a `Nat` that is guaranteed to have the same encoding/decoding as a `Nat`, while ensuring that it fits in a `U256` bits.
2. As an example, refactor `eth_fee_history` so that the public API only uses types from the new `evm_rpc_types` crate .
=> feat: `evm_rpc_types` crate and `Nat256`

Cargo.lock, Cargo.toml, evm_rpc_types/CHANGELOG.md, evm_rpc_types/Cargo.toml, evm_rpc_types/src/lib.rs, evm_rpc_types/src/request/mod.rs, evm_rpc_types/src/response/mod.rs, evm_rpc_types/src/tests.rs, src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/main.rs, src/types.rs, tests/tests.rs
Follow-up on #257 to move the types `GetLogsArgs` and `LogEntry` to the `evm_rpc_types` crate, so that the public API of `eth_get_logs` only uses types from that crate.
Additionally, add the types `Hex`, `Hex20`, and `Hex32` as a transparent wrapper around a Candid type `text` to represent Ethereum hex strings (prefixed by `0x`) containing an unbounded, 20 or 32 bytes, respectively.
=> refactor: move `GetLogsArgs` and `LogEntry` to the `evm_rpc_types` crate

README.md
- Incorrect Command: cd ic-eth-rpc
- Corrected Command: cd evm-rpc-canister This change ensures that the instructions align correctly with the cloned repository directory name.
=> Minor typo in the README.md

evm_rpc_types/CHANGELOG.md, evm_rpc_types/src/lib.rs, evm_rpc_types/src/request/mod.rs, evm_rpc_types/src/response/mod.rs, src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/main.rs, src/types.rs, tests/tests.rs
Follow-up on #257  to move the types `GetTransactionCountArgs` and `SendRawTransactionStatus` to the `evm_rpc_types` crate, so that the public API of `eth_get_transaction_count` and `eth_send_raw_transaction`, respectively,  only uses types from that crate.
=> refactor: move `GetTransactionCountArgs` and `SendRawTransactionStatus` to `evm_rpc_types`

Cargo.lock, evm_rpc_types/CHANGELOG.md, evm_rpc_types/Cargo.toml, evm_rpc_types/src/lib.rs, evm_rpc_types/src/rpc_client/mod.rs, src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/constants.rs, src/main.rs, src/providers.rs, src/types.rs, tests/tests.rs
Follow-up on #257 to move the following types to the `evm_rpc_types` crate:
1. `EthMainnetService`
2. `EthSepoliaService`
3. `HttpHeader`
4. `L2MainnetService`
5. `RpcApi`
6. `RpcConfig`
7. `RpcService`
8. `RpcServices`
so that the public API of all methods in `main.rs` only use types from that crate as arguments.
=> refactor: move types related to providers to `evm-rpc-types` crate

evm_rpc_types/CHANGELOG.md, evm_rpc_types/src/lib.rs, evm_rpc_types/src/result/mod.rs, evm_rpc_types/src/result/tests.rs, src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/http.rs, src/main.rs, src/providers.rs, src/types.rs, tests/tests.rs
Follow-up on #257 to move the following types to the `evm_rpc_types` crate:
1. `HttpOutcallError`
2. `JsonRpcError`
3. `MultiRpcResult`
4. `ProviderError`
5. `RpcError`,
6.   `RpcResult`
7. `ValidationError`
so that the public API of all methods in `main.rs` only use types from that crate as return types.
=> refactor: move types related to result to `evm-rpc-types`

candid/evm_rpc.did, scripts/build, src/main.rs, src/types.rs, tests/tests.rs
This PR renames the `InitArgs` type to `InstallArgs` for correctness, since it is used for both initialization and upgrades.
=> candid: rename `InitArgs` to `InstallArgs`

src/candid_rpc.rs, src/candid_rpc/cketh_conversion.rs, src/rpc_client/eth_rpc/mod.rs, src/rpc_client/eth_rpc_error/mod.rs, src/rpc_client/json/mod.rs, src/rpc_client/json/requests.rs, src/rpc_client/json/responses.rs, src/rpc_client/mod.rs, src/rpc_client/tests.rs
Follow-up on #279 to move JSON types into `src/rpc_client/json` and remove some unused code.
=> refactor: move types

Cargo.lock, Cargo.toml, candid/evm_rpc.did, evm_rpc_types/Cargo.toml, evm_rpc_types/src/lib.rs, evm_rpc_types/src/result/mod.rs, evm_rpc_types/src/rpc_client/mod.rs, src/arbitrary.rs, src/lib.rs, src/rpc_client/mod.rs, src/rpc_client/tests.rs, tests/tests.rs
Introduce a new parameter in `RpcConfig` to let the caller choose between different consensus strategies to aggregate answers from multiple providers. Two strategies are defined, with the possibility of adding more in the future:
1. `Equality`: this is the default and matches the current behaviour, where all responses are expected to be non-error cases and all responses are expected to be equal.
2. `Threshold`: new strategy introduced by this PR, allowing to relax the aforementioned equality strategy to only a subset of the responses. Choosing this strategy may influence the chosen providers to match the specified threshold parameters. The implementation of responses aggregation in this case is done in a separate PR (#287).
=> feat: Choose a consensus strategy

Cargo.lock, Cargo.toml, src/candid_rpc/cketh_conversion.rs, src/http_types/mod.rs, src/http_types/tests.rs, src/lib.rs, src/main.rs, src/rpc_client/eth_rpc/mod.rs, src/rpc_client/mod.rs, tests/tests.rs
Remove all productive dependencies on the [IC repository](https://github.com/dfinity/ic/tree/master):
1. `ic-canisters-http-types`: is removed and the corresponding types (`HttpRequest` and `HttpResponse`) were copied over since they amount to a few lines of code.
2. `ic-crypto-sha3`: is replaced by `ic-sha3`, available on [crates.io](https://crates.io/crates/ic-sha3).
3. `ic-ethereum-types` is replaced by a crate of the same name available on[ crates.io](https://crates.io/crates/ic-ethereum-types).
4. `ic-nervous-system-common`: is removed since it was only used to serve metrics.
The only remaining productive dependency from the IC repository is `ic-canister-log` and will be removed by #241.
=> chore: Remove dependencies on the IC repository

src/rpc_client/eth_rpc/mod.rs
Fix a bug introduced by #279, where the constant `HTTP_MAX_SIZE` was changed from 2 MB to 2 MiB. This is wrong since per the [IC specification ](https://internetcomputer.org/docs/current/references/ic-interface-spec#ic-http_request) `max_response_bytes` must be at most `2_000_000` bytes and HTTPs outcalls using a bigger value for `max_response_bytes` will be rejected.
=> fix: maximum value for `max_response_bytes`

CHANGELOG.md
Add a `CHANGELOG.md` file to keep track of changes accross releases. The section on `[2.0.0] - 2024-10-08` was copied from the [release notes](https://github.com/internet-computer-protocol/evm-rpc-canister/releases/tag/v2.0.0)
=> chore: add changelog file

.github/workflows/ci.yml, CHANGELOG.md, scripts/bootstrap
Add an action to
1. Run the script `./scripts/docker-build` that is in charge of the reproducible build.
2. Save the produced artifact so that it can be downloaded (e.g. for debugging purposes).
3. Display the SHA-256 of the produced artifact.
=> ci: Docker build on CI

evm_rpc_types/CHANGELOG.md, evm_rpc_types/src/lib.rs, evm_rpc_types/src/tests.rs
Improve `Debug` and `Display` implementations for `HexByte`, `Hex20`, `Hex32`, `Hex256`, `Hex` and `Nat256` to follow more closely the format of Ethereum instead of showing the internal representation (a byte array or a wrapper around a `Nat`)
=> refactor: improve debug and display representations

CHANGELOG.md, src/rpc_client/mod.rs, src/rpc_client/tests.rs, tests/tests.rs
`rpc.ankr.com` recently dropped its IPv6 connectivity and will need according to its support team a month to fix it (see this forum [post](https://forum.dfinity.org/t/cketh-a-canister-issued-ether-twin-token-on-the-ic/22819/204)) and is therefore unfit to be selected as a default provider in case the caller did not manually specify the requested providers. This PR replaces it with BlockPi (`ethereum.blockpi.network`), which has been so far working well for the [ckETH minter](https://dashboard.internetcomputer.org/canister/sv3dd-oaaaa-aaaar-qacoa-cai).
=> refactor: Remove Ankr as a default provider

CHANGELOG.md, Cargo.lock, candid/evm_rpc.did, evm_rpc_types/src/response/mod.rs, src/main.rs
Ensure that the declared Candid interface is the same as the one exposed by the canister.
=> fix: Candid interface compatibility

evm_rpc_types/CHANGELOG.md, evm_rpc_types/src/rpc_client/mod.rs, tests/tests.rs
1. Added missing `serde::Deserialize` annotation on `Provider`, `RpcAccess` and `RpcAuth` structs.
2. Add missing integration tests to ensure that every method on the Candid API is covered.
=> fix:  add missing `serde::Deserialize` annotation

CHANGELOG.md, src/rpc_client/mod.rs, src/rpc_client/tests.rs
Due to `Alchemy` low rate limit, switch the order of Ethereum mainnet providers between `Alchemy` and `LlamaNodes`.
=> fix: switch Alchemy with Llama nodes

.github/workflows/ci.yml, .github/workflows/conventional-commits.yml
Add a check to ensure that PR title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) format. Copied from https://github.com/dfinity/canbench/blob/255a422c02c3856195f04801efda7350cc061da3/.github/workflows/ci.yml.
=> ci: conventional commit checks

README.md
The management of providers was revamped in #252 and the provided commands in the README no longer apply.
=> docs: remove outdated authorization commands

candid/evm_rpc.did, evm_rpc_types/src/result/mod.rs, src/constants.rs, src/http.rs, src/metrics.rs, src/types.rs, src/validate.rs, tests/mock.rs, tests/tests.rs
Clean-up metrics:
1. removed because unused: `cyclesWithdrawn`, `errNoPermission` and `errHostNotAllowed`
2. Added `RejectionCode` to `errHttpOutcall` to be able to track all failed HTTPs outcalls at the protocol level (e.g. a `SysTransient` error is often due to the infamous `No consensus could be reached. Replicas had different responses`
3. Unify metrics related to memory to follow the convention of `stable_memory_bytes` and `heap_memory_bytes`
=> refactor: metrics

.github/workflows/ci.yml, candid/evm_rpc.did, dfx.json, evm_rpc_types/src/lib.rs, evm_rpc_types/src/lifecycle/mod.rs, scripts/e2e, scripts/examples, src/http.rs, src/main.rs, src/memory.rs, src/rpc_client/eth_rpc/mod.rs, src/types.rs, src/types/tests.rs, tests/tests.rs
Allow to override the URL that will be queried by the EVM RPC canister via a regex specified upon canister installation. This is allows testing against a local Ethereum development setup (such as [foundry](https://github.com/foundry-rs/foundry)) without changing the client calling the EVM RPC canister.
=> feat: allow to override provider url upon installation

.github/workflows/ci.yml, tests/tests.rs
1. Change the reproducible build job to use Ubuntu LTS (instead of latest)
2. Use the binary produced by the reproducible build job for integration tests with Pocket IC. Ideally the e2e should also use the same wasm, but this would require changing how `dfx.json` is setup and is out-of-scoped.
3. Run the pipeline 5 times successfully 🎉 .
=> fix: build pipeline

src/rpc_client/mod.rs
([XC-272](https://dfinity.atlassian.net/browse/XC-272)) Move Ankr to default ETH Sepolia services
Since Ankr seems to have fixed their IPv6 compatibility, move it to the list of default ETH Sepolia services, and move rpc.sepolia.org to non-default ETH Sepolia providers.
[XC-272]: https://dfinity.atlassian.net/browse/XC-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Move Ankr to default ETH Sepolia services

candid/evm_rpc.did, e2e/motoko/main.mo, evm_rpc_types/src/lifecycle/mod.rs, src/accounting.rs, src/constants.rs, src/http.rs, src/main.rs, src/memory.rs, src/rpc_client/eth_rpc/mod.rs, tests/tests.rs
XC-257
Fix the cycle computation according to the latest document on the cost for https outcalls https://internetcomputer.org/docs/current/developer-docs/gas-cost/#https-outcalls
Also add `nodesInSubnet` as an optional initialization parameter when creating the EVM RPC canister. It defaults to 34 if not set, which is also the default used previously.
=> fix: make subnet nodes configurable and fix https outcall cost calculation

.github/workflows/ci.yml
Remove `arduino/setup-protoc@v3` as it is actually not needed and triggers some rate limit.
=> ci: remove protoc

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, canhttp/Cargo.toml, canhttp/src/lib.rs, canhttp/src/observability/mod.rs, evm_rpc_types/src/request/mod.rs, evm_rpc_types/src/response/mod.rs, src/http.rs, src/main.rs, src/memory.rs, tests/tests.rs
Follow-up on #364 to add a new observability layer to take care of logging and metrics. Unfortunately, [`tower_http::trace`](https://docs.rs/tower-http/latest/tower_http/trace/index.html) cannot be used in a canister environment because it measures call latency with `Instant::now`. The proposed layer, while inspired by [`tower_http::trace`](https://docs.rs/tower-http/latest/tower_http/trace/index.html), is also simpler because it does not have to deal with streaming responses.
=> feat: observability layer

src/main.rs, tests/tests.rs
Ensure that calls to the HTTP endpoint in the EVM RPC canister in replicated mode are rejected.
=> fix: Reject calls to HTTP endpoint in replicated mode

scripts/bootstrap
The script `bootstrap` downloads the latest version of `rustup` to install the Rust toolchain, but its behavior changed with the latest version ([1.28.0](https://github.com/rust-lang/rustup/blob/5f3b27203d7ba5aaa27e3c53c3fdb611d98421bd/CHANGELOG.md)) so that the active Rust toolchain needs to be explicitly installed.
=> ci: fix reproducible build

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, canhttp/Cargo.toml, canhttp/src/client/mod.rs, canhttp/src/convert/mod.rs, canhttp/src/convert/request.rs, canhttp/src/convert/response.rs, canhttp/src/cycles/mod.rs, canhttp/src/filter_response/mod.rs, canhttp/src/http/json/mod.rs, canhttp/src/http/json/request.rs, canhttp/src/http/json/response.rs, canhttp/src/http/json/tests.rs, canhttp/src/http/mod.rs, canhttp/src/http/request.rs, canhttp/src/http/response.rs, canhttp/src/http/tests.rs, canhttp/src/json/mod.rs, canhttp/src/lib.rs, e2e/rust/src/main.rs, src/http.rs, src/main.rs, src/rpc_client/eth_rpc/mod.rs, src/rpc_client/json/requests.rs, src/rpc_client/json/responses.rs, src/rpc_client/mod.rs, tests/tests.rs
Follow-up on #370,  #364, and #374 to add a conversion layer between request and responses to handle [JSON RPC](https://www.jsonrpc.org/specification) over HTTP. 
Concretely:
1. Refactor existing infrastructure to handle errors explicitly, instead of having to downcast `BoxError`. This is beneficial since errors may happen at different layers and they all need to be handled by the above observability layer, e.g., add the corresponding metric in case the response has a non successful status.
2. Refactor existing infrastructure to transform request and response to use a single `Convert` trait to convert one type into another with some potential error.
3. Add a layer for `http::Request` and `http::Response` to transform their body into a JSON RPC type. This uses the above `Convert` trait. …
=> feat: JSON RPC conversion layer

canhttp/src/client/mod.rs, canhttp/src/client/tests.rs, canhttp/src/convert/error.rs, canhttp/src/convert/mod.rs, canhttp/src/http/mod.rs, canhttp/src/http/request.rs, canhttp/src/http/tests.rs, canhttp/src/lib.rs, canhttp/src/observability/mod.rs, canhttp/src/retry/mod.rs, canhttp/src/retry/tests.rs, src/http.rs, src/rpc_client/eth_rpc/mod.rs, tests/tests.rs
Follow-up on #370,  #364,  #374, and #375 to automatically retry requests by doubling its `max_response_bytes` when the response was too big.
=> feat: retry layer

canhttp/src/http/json/id.rs, canhttp/src/http/json/mod.rs, canhttp/src/http/json/request.rs, canhttp/src/http/json/response.rs, canhttp/src/http/json/tests.rs, canhttp/src/http/json/version.rs, canhttp/src/http/mod.rs, canhttp/src/http/response.rs, canhttp/src/lib.rs, e2e/motoko/main.mo, src/http.rs, src/memory.rs, src/rpc_client/eth_rpc/mod.rs, src/rpc_client/eth_rpc_error/mod.rs, src/rpc_client/eth_rpc_error/tests.rs, src/rpc_client/json/responses.rs, src/rpc_client/mod.rs, src/rpc_client/tests.rs
Refactor the JSON-RPC request and response types to follow the [specification](https://www.jsonrpc.org/specification) more closely:
1. `jsonrpc` must have the value `"2.0"`.
2. `id` must be a String, a number or a null value.
Left for a future PR: it should be ensured that the response ID matches the one from the request. This will be added as another tower middleware.
=> refactor: adapt JSON RPC request and response types according to the specification

canhttp/src/http/json/response.rs, canhttp/src/http/json/tests.rs
Add a `map` method to `canhttp::http::json::response::JsonRpcResponse`.
=> feat: add map method to `JsonRpcResponse`

canhttp/src/http/json/response.rs
Make `JsonRpcResponse` map able to return a different type instead of being restricted to the original result type.
=> feat: make `JsonRpcResponse` map able to return a different type

Cargo.lock, canhttp/Cargo.toml, canhttp/src/http/json/id.rs, canhttp/src/http/json/mod.rs, canhttp/src/http/json/request.rs, canhttp/src/http/json/tests.rs
Add a wrapper around a JSON-RPC request ID to ensure that the amount of bytes used when serialized to JSON is constant. 
This is necessary to ensure that two HTTPs outcalls for two JSON-RPC requests differing only by their IDs will have an identical cycle cost. See also dfinity/sol-rpc-canister#62.
=> feat(canhttp): JSON-RPC request ID with constant binary size

src/rpc_client/mod.rs
(XC-364) Since Ankr charges credits for RPC calls for Sepolia, move it down the list of default providers. Move PublicNode to the top spot since it is free. This means calls using a single provider will now make requests to PublicNode and hence avoid any credits being spent.
=> chore: re-order default Sepolia providers

e2e/motoko/main.mo, e2e/rust/src/main.rs, src/rpc_client/mod.rs
1. Cherry-pick #410 to move `PublicNode` as the first default provider for Ethereum Sepolia.
2. Cherry-pick #387 for `e2e/motoko/main.mo` and `e2e/rust/src/main.rs` to disable `Ankr` in end-to-end tests since an API key is required.
=> chore: re-order default Sepolia providers 

src/rpc_client/mod.rs, tests/tests.rs
Ankr was removed as a default provider in #305 due its drop in IPv6 connectivity which has since then been resolved. Meanwhile, `Cloudflare` consistently returns an error (`{ "jsonrpc": "2.0", "error": { "code": -32603, "message": "Internal error" }, "id": 1 }`) on any request since several weeks. This PR therefore put `Cloudflare` as last provider (by order of preference , since removing it would be a breaking change) and put back `Ankr` as the third default provider.
=> fix: replace Cloudflare with Ankr

mainnet/proposals/evm_rpc_2025_05_19.md
Proposal to upgrade to [v2.3.1](https://github.com/dfinity/evm-rpc-canister/releases/tag/v2.3.1) to swap Cloudflare with Ankr.
=> chore: proposal to upgrade to v2.3.1

src/main.rs, tests/tests.rs
Logs at level `TraceHttp` where not added to the canister response when queried via the HTTP endpoint `/logs`. Similar to dfinity/sol-rpc-canister#129.
=> fix: missing TraceHttp logs

CHANGELOG.md, Cargo.lock, Cargo.toml, canhttp/CHANGELOG.md, evm_rpc_types/CHANGELOG.md, evm_rpc_types/Cargo.toml
Update changelogs and bump version in preparation to the v2.4.0 release.
=> chore: release v2.4.0

mainnet/proposals/evm_rpc_20256_06_06.md
Proposal to upgrade the EVM RPC canister [`7hfb6-caaaa-aaaar-qadga-cai`](https://dashboard.internetcomputer.org/canister/7hfb6-caaaa-aaaar-qadga-cai) to [v2.4.0](https://github.com/dfinity/evm-rpc-canister/releases/tag/v2.4.0).
=> chore: proposal to upgrade to v2.4.0

src/main.rs, src/providers.rs, src/providers/tests.rs, src/rpc_client/mod.rs, src/rpc_client/tests.rs, src/types.rs
The notion of default/non-default providers was only useful when Equality was chosen as consensus strategy and no providers was explicitly specified, in which case the "default" providers would be selected. This PR removes the notion of default/non-default providers by replacing with an ordered list of providers for a given EVM chain, corresponding to the supported providers. The previous notion of "default" providers simply correspond to the first three providers in that list.
This is similar to the refactoring done in dfinity/sol-rpc-canister#122.
Differentiating between supported and custom providers is the first step towards dynamically ranking supported providers according to the number of their successful responses, which is done in the following 3 PRs:
1. #436 (this one)
2. #434 …
=> refactor: remove default/non-default providers

evm_rpc_types/src/result/mod.rs, evm_rpc_types/src/result/tests.rs
Previously, `MultiRpcResult::map` always returned `Consistent` → `Consistent` and `Inconsistent` → `Inconsistent`. With non-injective functions, this could produce an `Inconsistent` variant whose results were all equal.
This change updates `map` so that after applying the function, any `Inconsistent` results that are all equal are collapsed into a single `Consistent` result. 
A new `collapse` performing this operation is also added to `MultiRpcResult`.
=> fix: `MultiRpcResult::map` for non-injective functions

candid/evm_rpc.did, src/http.rs, src/types/mod.rs, tests/tests.rs
([XC-482](https://dfinity.atlassian.net/browse/XC-482)) Currently, the error metrics are incremented on all `SYS_FATAL` error responses. However, this error also occurs when the response size exceeds `max_response_bytes`, which is a client error. As such, a new dedicated metric for `max_response_bytes` exceeded is added, and separated from other IC error metrics.
[XC-482]: https://dfinity.atlassian.net/browse/XC-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: handle `max_response_bytes` is exceeded error in metrics

candid/evm_rpc.did, evm_rpc_types/src/response/mod.rs, src/candid_rpc/cketh_conversion.rs, src/rpc_client/json/responses.rs, src/rpc_client/tests.rs, tests/tests.rs
(XC-412) Add support for the `root` and `cumulativeGasUsed` fields in the response to `eth_getTransactionReceipt`: 
* The `root` field is mandatory for transactions included pre-Byzantium and represents the post-transaction state root.
* The `cumulativeGasUsed` is mandatory for all transactions and represents the sum of gas used by this transaction and all preceding transactions in the same block.
This is **not** breaking for the canister Candid API since adding a new field to a returned type is not breaking. 
BREAKING: This is only breaking for the `evm_rpc_types` crate since it adds new fields to the public `evm_rpc_types::TransactionsReceipt` type.
=> feat!: add support for `eth_getTransactionReceipt` response fields

.github/workflows/publish.yml, .github/workflows/release.yml, cliff.toml, release-plz.toml, release_notes.md
Add release and publish GitHub pipelines with `release-plz` to automate the creation of new releases.
=> ci: add release and publish pipelines

src/metrics.rs, tests/tests.rs
This PR fixes a bug where `Metrics::err_max_response_size_exceeded` was not encoded in the Prometheus metrics.
=> fix: add `err_max_response_size_exceeded` to Prometheus metrics

src/main.rs
(XC-502) This PR removes unnecessary `#[candid_method]` annotations on the EVM RPC canister endpoint definitions. These annotations are redundant with the existing `#[query]` and `#[update]` annotations.
=> refactor: remove unnecessary `#[candid_method]` annotations
